### ISSUE TITLE
Support for Mac

### ISSUE THREAD

**Issue by ian-coccimiglio** [True-North-Intelligent-Algorithms/napari-segment-everything#5]
Currently a lot of this implementation requires CUDA. When testing on an M1 mac, the test-suite tends to fail on torch functions - test_mobile_sam, test_RCNN, test_YOLO, and test_labels.

Plan to address:
- Swap functions from CUDA torch to variable, and vary the device as a parameter to each function
- Determine whether any of the models require compilation through CUDA.

**Comment by bnorthan** [comment]
There is a little utility that was copied from the Royer lab code, that I use to get the device type.  See [here](https://github.com/True-North-Intelligent-Algorithms/napari-segment-everything/blob/main/src/napari_segment_everything/sam_helper.py#L105).

In this case I think mps is a torch implementation for Mac GPU https://pytorch.org/docs/stable/notes/mps.html

However where it might get a bit annoying is that after talking to @psobolewskiPhD I believe that mps does not have 64 bit floating point support and SAM needs this in a couple of places.  However I also understand that microsam may have vendored a bunch of code, and made a couple of trivial changes. 


Could be relevant https://computational-cell-analytics.github.io/micro-sam/micro_sam.html#from-source

Also looking over the microsam issue they are discussing a couple Mac M1/M2/M3 issues https://github.com/computational-cell-analytics/micro-sam/issues/435

**Comment by ian-coccimiglio** [comment]
I did some testing, and I believe we can route around the MPS problems. Our setup performs decently on Mac M1, even if we're mostly using the CPU.

The following pipeline works:
1) Create bounding boxes with YOLOv8 using MPS (which is about 25% faster than CPU)
2) Prompt SAM on the CPU (or on MPS - from my testing, 32-bit bounding-box/point tensors are valid inputs to the SAM predictor, but I'll look at developing some tests to ensure that results are consistent.)

My testing suggests that 600-700 bounding-boxes on a 1200x1800 image can be segmented in 30 seconds on a Macbook M1 Air, even when segmenting on CPU. Not as fast as I'd like, but it could probably be optimized.

**Comment by ian-coccimiglio** [comment]
OK, so I think I figured out some of the issues with the Github integration testing
1) I'm not sure if Github's test runners actually have any available MPS GPU memory. I'm pretty confused about it, but any test code that assumes MPS seems to fail the testing. I think the best way to resolve this would be to have a function which checks if the code is being run in a test_runner, but for now I've put in a kludge to have the testing code run only on either CUDA or CPU.
2) Python 3.8 doesn't support the type hinting syntax used in mobileSAMv2, specifically the list[float] syntax. This will also fail when running the plugin locally - so we should maybe suggest the package requires Python >=3.9
